let currentItem = null, score = 0;
const scoreSpan = document.getElementById('scoreValue'), emojiSpan = document.getElementById('itemEmoji'), optionsDiv = document.getElementById('optionsContainer'), hintBtn = document.getElementById('listenHintBtn'), nextBtn = document.getElementById('nextBtn'), feedback = document.getElementById('feedbackContainer');
async function fetchItem() { const res = await fetch('api.php?action=getItem&activity=ispy'); const data = await res.json(); if(data.success) { currentItem = data.item; emojiSpan.innerText = currentItem.emoji; generateOptions(); } }
async function fetchScore() { const res = await fetch('api.php?action=getScore'); const data = await res.json(); score = data.score; scoreSpan.innerText = score; }
function showToast(msg, ok) { feedback.innerHTML = ''; const t = document.createElement('div'); t.className = `feedback-toast px-4 py-2 rounded-full text-white ${ok ? 'bg-green-500' : 'bg-red-500'}`; t.innerText = msg; feedback.appendChild(t); setTimeout(() => t.remove(), 2000); }
function generateOptions() { const all = ['Apple','Ball','Cat','Dog','Sun','Fish']; let opts = [currentItem.word, ...all.filter(w => w !== currentItem.word).sort(()=>Math.random()-0.5).slice(0,2)]; opts.sort(()=>Math.random()-0.5); optionsDiv.innerHTML = ''; opts.forEach(opt => { const btn = document.createElement('button'); btn.innerText = opt; btn.className = 'bg-gray-200 p-2 rounded-full'; btn.onclick = () => checkAnswer(opt); optionsDiv.appendChild(btn); }); }
async function checkAnswer(selected) { const fd = new FormData(); fd.append('action','check'); fd.append('activity','ispy'); fd.append('resposta',selected); const res = await fetch('api.php',{method:'POST',body:fd}); const data = await res.json(); if(data.success) { showToast(data.feedback, data.feedback.includes('Great')); score = data.score; scoreSpan.innerText = score; if(data.feedback.includes('Great')) { await nextItem(); } } }
function playHint() { const u = new SpeechSynthesisUtterance(`I spy with my little eye... something that ${currentItem.hint}`); u.lang = 'en-US'; speechSynthesis.speak(u); }
async function nextItem() { await fetch('api.php?action=next&activity=ispy'); await fetchItem(); }
hintBtn.onclick = playHint; nextBtn.onclick = nextItem; fetchItem(); fetchScore();